package codegen

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// The canonical example is regenerated by the production CLI; all existing
// Swift/Kotlin files remain byte-identical. Java alone migrates its source API.
func TestCounterWriterGeneratedPackages(t *testing.T) {
	// Frozen from independently built facade 48ac13b9 (v0.4.7), before
	// composition. The sole authorized delta is the ordinary Java skeleton.
	raw, e := os.ReadFile("testdata/counter-writer-preserved-v047.json")
	if e != nil {
		t.Fatal(e)
	}
	var preserved map[string]string
	if e := json.Unmarshal(raw, &preserved); e != nil {
		t.Fatal(e)
	}
	root := t.TempDir()
	cmd := exec.Command("go", "run", "./cmd/jcrpc-gen", "--all", "--out-dir", root, "../examples/counter/counter.toml")
	if b, e := cmd.CombinedOutput(); e != nil {
		t.Fatalf("generate: %v\n%s", e, b)
	}
	count := 0
	e = filepath.WalkDir(root, func(path string, d os.DirEntry, e error) error {
		if e != nil || d.IsDir() {
			return e
		}
		rel, e := filepath.Rel(root, path)
		if e != nil {
			return e
		}
		got, e := os.ReadFile(path)
		if e != nil {
			return e
		}
		if strings.HasSuffix(rel, "Skeleton.java") && !strings.Contains(string(got), "public final short dispatchTo(") {
			t.Error("ordinary writer entry missing")
		}
		if !strings.HasSuffix(rel, "Skeleton.java") {
			if preserved[filepath.ToSlash(rel)] != fmt.Sprintf("%x", sha256.Sum256(got)) {
				t.Errorf("preserved generated bytes changed: %s", rel)
			}
		}
		count++
		return nil
	})
	if e != nil {
		t.Fatal(e)
	}
	if count != 9 {
		t.Fatalf("inventory %d, want 9", count)
	}
	if len(preserved) != 8 {
		t.Fatal("incomplete preserved inventory")
	}
}

// Source inspection complements the behavioral suite: command paths cannot
// allocate arrays, and neither example class may retain an APDU/buffer field.
// It is not a JCRE allocation or physical-card measurement.
func TestCounterWriterSourceOwnership(t *testing.T) {
	for file, methods := range map[string][]string{
		"CounterJCApplet.java": {"process"},
		"CounterApplet.java":   {"onGetInfo", "onStore", "onLoad", "onGetSpki", "onGetImsi", "onGetAppletInfo", "onSignChallenge", "onGetDisplayName", "onEchoMessage", "writeBytes"},
	} {
		b, e := os.ReadFile(filepath.Join("../examples/counter/applet/src/main/java/io/jcrpc/example", file))
		if e != nil {
			t.Fatal(e)
		}
		for _, method := range methods {
			if strings.Contains(javaMethodBody(t, string(b), method), "new ") {
				t.Fatalf("allocation in %s.%s", file, method)
			}
		}
		if strings.Contains(string(b), "private final APDU") || strings.Contains(string(b), "private APDU") {
			t.Fatal("retained APDU")
		}
		for _, hostAPI := range []string{"Math.", "System.arraycopy", "UnsupportedOperationException"} {
			if strings.Contains(string(b), hostAPI) {
				t.Fatalf("host-only API in %s: %s", file, hostAPI)
			}
		}
	}
}

// Drives CounterJCApplet.process -> regenerated CounterSkeleton.dispatchTo
// using a bounded APDU fragment model, including conditions the simulator does
// not expose. Separate Gradle tests exercise real JCRE sends; no physical claim.
func TestCounterWriterAPDUContract(t *testing.T) { runCounterWriterHarness(t, "", "") }

// Each plant keeps its gate/token and admits one forbidden class; the same
// executable consumer suite must fail at its named assertion, never at javac.
func TestCounterWriterNarrowingMutants(t *testing.T) {
	for _, m := range []struct{ name, file, before, after, diagnostic string }{
		{"last-fragment-omitted", "CounterJCApplet.java", "while (received < requestLength)", "while (received < requestLength - 1)", "fragmented-store receive"},
		{"zero-fragment-spins", "CounterJCApplet.java", "fragment <= 0", "fragment < 0", "zero fragment not rejected"},
		{"extended-two-byte-admitted", "CounterJCApplet.java", "requestOffset != ISO7816.OFFSET_CDATA", "(requestOffset != ISO7816.OFFSET_CDATA && requestLength != 2)", "extended request admitted"},
		{"length-one-over-capacity", "CounterApplet.java", "length > capacity", "length > capacity + 1", "variable refusal wrote output"},
		{"request-one-over-buffer", "CounterJCApplet.java", "requestLength > buffer.length - requestOffset", "(requestLength > buffer.length - requestOffset && requestLength != 129)", "request capacity reached receive"},
		{"length-256-admitted", "CounterJCApplet.java", "requestLength > 255", "requestLength > 256", "extended length admitted status"},
		{"fragment-one-over-remaining", "CounterJCApplet.java", "fragment > requestLength - received", "fragment > requestLength - received + 1", "excess fragment admitted"},
		// Preserves dispatchTo and send tokens; behavior alone detects wrong span.
		{"send-omits-last-byte", "CounterJCApplet.java", "setOutgoingAndSend(outputOffset, produced)", "setOutgoingAndSend(outputOffset, (short) (produced - 1))", "scalar wire"},
	} {
		t.Run(m.name, func(t *testing.T) {
			b, e := os.ReadFile(filepath.Join("../examples/counter/applet/src/main/java/io/jcrpc/example", m.file))
			if e != nil {
				t.Fatal(e)
			}
			if strings.Count(string(b), m.before) != 1 {
				t.Fatal("plant not unique")
			}
			mutated := strings.Replace(string(b), m.before, m.after, 1)
			runCounterWriterHarness(t, m.file, mutated, m.diagnostic)
		})
	}
}

func runCounterWriterHarness(t *testing.T, mutantFile, mutantSource string, expected ...string) {
	t.Helper()
	root := t.TempDir()
	paths := []string{writeJavaCardJCSystemStub(t, root)}
	for name, content := range map[string]string{
		"javacard/framework/Applet.java":       counterAppletStub,
		"javacard/framework/ISO7816.java":      counterISOStub,
		"javacard/framework/ISOException.java": counterExceptionStub,
		"javacard/framework/APDU.java":         counterAPDUStub,
		"javacard/framework/Util.java":         counterUtilStub,
		"CounterWriterHarness.java":            counterWriterHarness,
	} {
		p := filepath.Join(root, name)
		if e := os.MkdirAll(filepath.Dir(p), 0755); e != nil {
			t.Fatal(e)
		}
		writeTestFile(t, p, []byte(content))
		paths = append(paths, p)
	}
	for _, name := range []string{"CounterApplet.java", "CounterJCApplet.java"} {
		b, e := os.ReadFile(filepath.Join("../examples/counter/applet/src/main/java/io/jcrpc/example", name))
		if e != nil {
			t.Fatal(e)
		}
		if name == mutantFile {
			b = []byte(mutantSource)
		}
		p := filepath.Join(root, name)
		writeTestFile(t, p, b)
		paths = append(paths, p)
	}
	schema, e := ParseFile("../examples/counter/counter.toml")
	if e != nil {
		t.Fatal(e)
	}
	generated, e := GenerateJavaSkeleton(schema, "counter")
	if e != nil {
		t.Fatal(e)
	}
	for name, b := range map[string][]byte{"CounterSkeleton.java": generated.SkeletonSource, "CounterTransport.java": generated.TransportSource} {
		p := filepath.Join(root, name)
		writeTestFile(t, p, b)
		paths = append(paths, p)
	}
	if b, e := exec.Command("javac", append([]string{"-d", root}, paths...)...).CombinedOutput(); e != nil {
		t.Fatalf("compile (not a kill): %v\n%s", e, b)
	}
	cmd := exec.Command("java", "-cp", root, "CounterWriterHarness")
	b, e := cmd.CombinedOutput()
	if len(expected) > 0 {
		if e == nil || !strings.Contains(string(b), expected[0]) {
			t.Fatalf("survivor/unrelated failure: %v\n%s; want %s", e, b, expected[0])
		}
		t.Logf("killed by TestCounterWriterAPDUContract: %s; child exit %d", expected[0], cmd.ProcessState.ExitCode())
	} else if e != nil {
		t.Fatalf("consumer: %v\n%s", e, b)
	}
}

const counterAppletStub = `package javacard.framework;
public abstract class Applet {
 public static Applet installed;
 protected void register() { installed=this; }
 protected boolean selectingApplet() { return false; }
 public abstract void process(APDU apdu);
}`
const counterISOStub = `package javacard.framework;
public interface ISO7816 {
 short OFFSET_CLA=0, OFFSET_INS=1, OFFSET_P1=2, OFFSET_P2=3, OFFSET_CDATA=5;
 short SW_CLA_NOT_SUPPORTED=(short)0x6E00, SW_WRONG_LENGTH=(short)0x6700, SW_INS_NOT_SUPPORTED=(short)0x6D00;
}`
const counterUtilStub = `package javacard.framework;
public final class Util {
 public static short arrayCopyNonAtomic(byte[] src,short from,byte[] dst,short at,short len){System.arraycopy(src,from,dst,at,len);return (short)(at+len);}
}`
const counterExceptionStub = `package javacard.framework;
public class ISOException extends RuntimeException {
 public final short sw; private ISOException(short sw) { this.sw=sw; }
 public static void throwIt(short sw) { throw new ISOException(sw); }
}`
const counterAPDUStub = `package javacard.framework;
public final class APDU {
 public final byte[] buffer; public byte[] sent; public int sends, reads;
 private final byte[] data; private final int declared, offset; private final int[] fragments;
 private int consumed;
 public APDU(int ins,int p1,byte[] data,int declared,int offset,int capacity,int... fragments) {
  buffer=new byte[capacity]; buffer[0]=(byte)0xB0; buffer[1]=(byte)ins; buffer[2]=(byte)p1;
  this.data=data; this.declared=declared; this.offset=offset; this.fragments=fragments;
 }
 public byte[] getBuffer(){return buffer;}
 public short getIncomingLength(){return (short)declared;}
 public short getOffsetCdata(){return (short)offset;}
 public short setIncomingAndReceive(){ short n=receiveBytes((short)offset); buffer[1]=(byte)0x7F; buffer[2]=0; return n; }
 public short receiveBytes(short at){
  if(reads>10)throw new AssertionError("zero fragment not rejected");
  int n=reads<fragments.length?fragments[reads]:0; reads++;
  if(n>0){if(at+n>buffer.length)throw new AssertionError("request capacity reached receive");System.arraycopy(data,consumed,buffer,at,n); consumed+=n;}
  return (short)n;
 }
 public void setOutgoingAndSend(short at,short count){ sends++; sent=new byte[count]; System.arraycopy(buffer,at,sent,0,count); }
}`
const counterWriterHarness = `import java.util.Arrays;
import javacard.framework.*;
import counter.CounterSkeleton;
import io.jcrpc.counter.example.*;

public class CounterWriterHarness {
 static CounterJCApplet app;
 static byte[] empty=new byte[0];
 static void check(boolean ok,String message){if(!ok)throw new AssertionError(message);}
 static APDU frame(int ins,int p1,byte[] data,int declared,int offset,int cap,int... chunks){return new APDU(ins,p1,data,declared,offset,cap,chunks);}
 static APDU valid(int ins,int p1,byte[] data,int... chunks){APDU a=frame(ins,p1,data,data.length,5,133,chunks);app.process(a);return a;}
 static void reject(APDU a,int sw,String message){
  try{app.process(a);throw new AssertionError(message);}catch(ISOException e){check((e.sw&65535)==sw,message+" status");}
  check(a.sends==0,message+" sent bytes");
 }
 public static void main(String[] args){
  CounterJCApplet.install(empty,(short)0,(byte)0); app=(CounterJCApplet)Applet.installed;
  scalarAndVoid(); fragmentedStore(); fragmentedEchoAndSignature(); malformedReceive(); directSpans();
 }
 // Real process -> dispatchTo must capture P1, return exact scalar wire and
 // preserve counter state after wrong request length/business rejection.
 static void scalarAndVoid(){
  APDU a=valid(1,5,empty,0);check(Arrays.equals(a.sent,new byte[]{0,5}),"scalar wire");
  reject(frame(1,7,new byte[]{1},1,5,133,1),0x6700,"unexpected scalar data admitted");
  check(Arrays.equals(valid(3,0,empty,0).sent,new byte[]{0,5}),"bad request mutated counter");
  a=valid(4,0,empty,0);check(a.sends==0,"void sent bytes");
  valid(5,0,new byte[]{0,3},1,1);
  reject(frame(1,4,empty,0,5,133,0),0x6986,"business failure admitted");
  check(Arrays.equals(valid(3,0,empty,0).sent,new byte[]{0,0}),"business failure mutated counter");
 }
 // Fits exactly 128 bytes at offset 5 in a 133-byte request buffer. The
 // store/load control detects skipped final fragments and preserves old data
 // when the business limit rejects its neighboring 129-byte input.
 static void fragmentedStore(){
  byte[] bytes=new byte[128];for(int i=0;i<128;i++)bytes[i]=(byte)(i+1);
  APDU a=valid(7,0,bytes,1,126,1);check(a.sends==0&&a.reads==3,"fragmented-store receive");
  check(Arrays.equals(valid(8,0,empty,0).sent,bytes),"fragmented-store wire");
  byte[] tooLong=new byte[129];reject(frame(7,0,tooLong,129,5,256,129),0x6A80,"oversize store admitted");
  check(Arrays.equals(valid(8,0,empty,0).sent,bytes),"rejected store lost prior data");
 }
 // Same-buffer output must consume borrowed bytes before overlap; signature
 // expectations are independent of the production packing implementation.
 static void fragmentedEchoAndSignature(){
  byte[] bytes=new byte[]{(byte)0xD0,(byte)0x9F,1,2,3,4,5,6,7,8,9,10};
  check(Arrays.equals(valid(14,0,bytes,3,8,1).sent,bytes),"borrowed echo wire");
  byte[] challenge=new byte[]{1,2,3,4,5,6,7,8,9,10};
  byte[] expected=new byte[22];expected[0]=0x30;expected[1]=20;expected[2]=2;expected[3]=8;
  for(int i=0;i<8;i++){expected[4+i]=(byte)(challenge[i]^1);expected[14+i]=(byte)(challenge[9-i]^3^0x5A);}
  expected[12]=2;expected[13]=8;expected[4]&=0x7F;expected[14]&=0x7F;
  check(Arrays.equals(valid(12,0,challenge,1,8,1).sent,expected),"borrowed signature wire");
  reject(frame(12,0,empty,0,5,133,0),0x6700,"empty challenge admitted");
 }
 // Explicit unsupported/truncated/overreported receive cases reject before
 // dispatch/send. Valid two-byte fragmented setLimit is the nearby control.
 static void malformedReceive(){
  reject(frame(5,0,new byte[]{0,4},2,5,133,1,0),0x6700,"truncated request dispatched");
  reject(frame(5,0,new byte[]{0,4},2,5,133,1,-1),0x6700,"negative fragment admitted");
  reject(frame(5,0,new byte[]{0,4,5},2,5,133,1,2),0x6700,"excess fragment admitted");
  reject(frame(5,0,new byte[]{0,4},2,7,133,1,1),0x6700,"extended request admitted");
  reject(frame(7,0,new byte[129],129,5,133,1,128),0x6700,"request capacity admitted");
  APDU extended=frame(7,0,new byte[256],256,5,300,1);
  reject(extended,0x6700,"extended length admitted");
  check(extended.reads==1,"extended length admitted status");
  reject(frame(5,0,new byte[]{0},1,5,133,1),0x6700,"short fixed request admitted");
  reject(frame(5,0,new byte[]{0,4,5},3,5,133,3),0x6700,"long fixed request admitted");
  reject(frame(0x7F,0,empty,0,5,133,0),0x6D00,"unknown INS admitted");
  check(Arrays.equals(valid(3,0,empty,0).sent,new byte[]{0,0}),"receive rejection changed counter");
  reject(frame(6,0,empty,0,5,6,0),0x6700,"packed output capacity admitted");
 }
 static class Tracking extends CounterApplet{
  int calls;
  protected short onGetInfo(byte[] out,short off,short cap){calls++;check(cap==7,"fixed callback capacity");return super.onGetInfo(out,off,cap);}
 }
 static short dispatch(CounterApplet logic,int ins,byte[] in,short inOff,short len,byte[] out,short off,short cap){return logic.dispatchTo((byte)ins,(byte)0,(byte)0,in,inOff,len,out,off,cap);}
 static void spanReject(CounterApplet logic,int ins,byte[] in,short inOff,short len,byte[] out,short off,short cap,String message){
  try{dispatch(logic,ins,in,inOff,len,out,off,cap);throw new AssertionError(message);}catch(CounterSkeleton.StatusWordException e){check((e.getStatusWord()&65535)==0x6700,message+" status");}
 }
 // Call the generated production entry directly to expose caller window
 // bounds the real APDU API cannot supply. Fixed capacity rejects before a
 // tracking callback; the successful exact-width control must enter it once.
 static void directSpans(){
  Tracking logic=new Tracking();byte[] out=new byte[133];Arrays.fill(out,(byte)0x55);
  spanReject(logic,6,null,(short)0,(short)0,out,(short)7,(short)6,"fixed insufficient capacity admitted");
  spanReject(logic,6,null,(short)0,(short)0,null,(short)0,(short)7,"null output admitted");
  spanReject(logic,6,null,(short)0,(short)0,out,(short)-1,(short)7,"negative output offset admitted");
  spanReject(logic,6,null,(short)0,(short)0,out,(short)133,(short)1,"output overrun admitted");
  spanReject(logic,6,out,(short)134,(short)0,out,(short)7,(short)7,"input overrun admitted");
  spanReject(logic,6,null,(short)1,(short)0,out,(short)7,(short)7,"invalid null request admitted");
  check(logic.calls==0,"fixed callback entered on refusal");for(byte b:out)check(b==0x55,"rejected fixed output write");
  check(dispatch(logic,6,null,(short)0,(short)0,out,(short)7,(short)100)==7&&logic.calls==1,"fixed callback valid control");
  check(out[6]==0x55&&out[14]==0x55,"output neighbors overwritten");
  byte[] before=out.clone();
  spanReject(logic,10,null,(short)0,(short)0,out,(short)7,(short)14,"variable insufficient capacity admitted");
  check(Arrays.equals(before,out),"variable refusal wrote output");
  check(dispatch(logic,10,null,(short)0,(short)0,out,(short)7,(short)15)==15,"variable exact capacity control");
 }
}`
